// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	contextx "github.com/blackhorseya/amazingtalker/internal/pkg/contextx"
	mock "github.com/stretchr/testify/mock"

	pb "github.com/blackhorseya/amazingtalker/pb"
)

// IBiz is an autogenerated mock type for the IBiz type
type IBiz struct {
	mock.Mock
}

// GetInfoBySlug provides a mock function with given fields: ctx, slug
func (_m *IBiz) GetInfoBySlug(ctx contextx.Contextx, slug string) (*pb.Tutor, error) {
	ret := _m.Called(ctx, slug)

	var r0 *pb.Tutor
	if rf, ok := ret.Get(0).(func(contextx.Contextx, string) *pb.Tutor); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.Tutor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListByLangSlug provides a mock function with given fields: ctx, slug
func (_m *IBiz) ListByLangSlug(ctx contextx.Contextx, slug string) ([]*pb.Tutor, error) {
	ret := _m.Called(ctx, slug)

	var r0 []*pb.Tutor
	if rf, ok := ret.Get(0).(func(contextx.Contextx, string) []*pb.Tutor); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pb.Tutor)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(contextx.Contextx, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
