// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package tutors

import (
	"github.com/blackhorseya/amazingtalker/internal/biz/tutors"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateIHandler(biz tutors.IBiz) (IHandler, error) {
	iHandler := NewImpl(biz)
	return iHandler, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
