apiVersion: apps/v1
kind: Deployment
metadata:
  name: q1
  labels:
    app: q1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: q1
  template:
    metadata:
      labels:
        app: q1
    spec:
      containers:
        - name: q1
          image: q1:latest
          ports:
            - containerPort: 8080
