// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package counter

import (
	"github.com/blackhorseya/ip-rate-limit/internal/app/biz/counter"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateHandler(biz counter.IBiz) (IHandler, error) {
	iHandler := NewImpl(biz)
	return iHandler, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
