// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package health

import (
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateHandler() (IHandler, error) {
	iHandler := NewImpl()
	return iHandler, nil
}

// wire.go:

var testProviderSet = wire.NewSet(NewImpl)
